// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyApi.Data;

#nullable disable

namespace PharmacyApi.Migrations
{
    [DbContext(typeof(PharmacyContext))]
    partial class PharmacyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyApi.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Cipla",
                            ExpiryDate = new DateTime(2026, 11, 4, 15, 8, 39, 376, DateTimeKind.Utc).AddTicks(9755),
                            FullName = "Paracetamol 500mg",
                            Notes = "For fever and mild pain relief",
                            Price = 25.50m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Sun Pharma",
                            ExpiryDate = new DateTime(2026, 7, 22, 15, 8, 39, 376, DateTimeKind.Utc).AddTicks(9781),
                            FullName = "Amoxicillin 250mg",
                            Notes = "Antibiotic - complete full course",
                            Price = 120.00m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dr. Reddy's",
                            ExpiryDate = new DateTime(2027, 1, 23, 15, 8, 39, 376, DateTimeKind.Utc).AddTicks(9787),
                            FullName = "Cetirizine 10mg",
                            Notes = "Antihistamine for allergies",
                            Price = 15.75m,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("PharmacyApi.Models.SaleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Buyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPriceAtSale")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.ToTable("SaleRecords");
                });

            modelBuilder.Entity("PharmacyApi.Models.SaleRecord", b =>
                {
                    b.HasOne("PharmacyApi.Models.Medicine", "Medicine")
                        .WithMany("SaleRecords")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyApi.Models.Medicine", b =>
                {
                    b.Navigation("SaleRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
